#### Numpy is similar to list array then why do we use numpy?

3 main benefits of numPy over python list
1) Less memory
2) Fast
3) Convinient

In [1]:
import numpy as np
import time
import sys

In [6]:
# Create a list
l=range(1000)
print(sys.getsizeof(5)*len(l))

28000


In [5]:
array=np.arange(1000)
array.nbytes

4000

In [7]:
array.size*array.itemsize

4000

##### To check numpy is fast in comapre to List

In [9]:
SIZE=1000

#### for list calculation

In [10]:
l1=range(SIZE)
l2=range(SIZE)

start=time.time()
result=[(x+y)for x,y in zip(l1,l2)]
print("python list took time: ",(time.time()-start)*1000)

python list took tme:  0.9989738464355469


#### for Numpy calculation

In [11]:
a1=np.arange(SIZE)
a2=np.arange(SIZE)
start=time.time()
result= a1+a2
print("Numpy took time ",(time.time()-start)*1000)


Numpy took time  0.9970664978027344


In [16]:
SIZE=1000000

In [17]:
l1=range(SIZE)
l2=range(SIZE)

start=time.time()
result=[(x+y)for x,y in zip(l1,l2)]
print("python list took time: ",(time.time()-start)*1000)

python list took time:  194.47994232177734


In [18]:
a1=np.arange(SIZE)
a2=np.arange(SIZE)
start=time.time()
result= a1+a2
print("Numpy took time ",(time.time()-start)*1000)

Numpy took time  22.937536239624023


##### So by above exmaple we can say that numpy take less time to execute function
also convenient as well like to add just use a1+a2 while for list to add we use some trciky codes

### numpy Basic array operation

define multi dimesniionla array

In [19]:
#1d
a=np.array([1,2,3])
a.ndim

1

In [20]:
#2d
a=np.array([[1,2],[3,4],[5,6]])
a.ndim

2

In [21]:
#3d
a=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
a.ndim

3

In [23]:
#4d
a=np.array([[[[1,2],[3,4]],[[5,6],[7,8]]],[[[1,2],[3,4]],[[5,6],[7,8]]]])
a.ndim

4

In [32]:
print(a.itemsize) # for integer element itemsize will 4 bytes while for float it would be 8 bytes

print(a.dtype)

4
int32


In [27]:
b=np.array([5.0,6.0,7.0])
b.itemsize

8

In [33]:
# if integer and float both then it will consider all element as higher side that is float and will give itemsize as per higher memeory side means of float
c=np.array([5,6.0,7.0])
c.itemsize

8

In [36]:
# if want to change data type as per users:
t= np.array([1,2,3],dtype='float64')
print(t.itemsize)
print(t)

8
[1. 2. 3.]


In [37]:
# if you want then change data type from int o float to complexnum as well
t= np.array([1,2,3],dtype=complex)
print(t.itemsize)
print(t)

16
[1.+0.j 2.+0.j 3.+0.j]


In [38]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [39]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [40]:
l=range(5)
l

range(0, 5)

In [41]:
a=np.arange(5)
a

array([0, 1, 2, 3, 4])

In [42]:
np.arange(1,5)

array([1, 2, 3, 4])

In [43]:
np.arange(1,5,2)

array([1, 3])

In [44]:
np.linspace(1,5,10)

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

#### reshape of array

In [46]:
a=np.array([[1,2,3],[4,5,6]])
a.shape

(2, 3)

In [47]:
a.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

#### User ravel to flatten your array in one dimension

In [49]:
a.ravel()

array([1, 2, 3, 4, 5, 6])

#### mathematical function

In [50]:
np.min(a)

1

In [51]:
a.min()

1

In [52]:
np.sum(a,axis=0)# axis=0 for column

array([5, 7, 9])

In [53]:
np.sum(a,axis=1)# axis=1 for rows

array([ 6, 15])

In [54]:
np.sqrt(a)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [55]:
np.sin(a)

array([[ 0.84147098,  0.90929743,  0.14112001],
       [-0.7568025 , -0.95892427, -0.2794155 ]])

In [56]:
a=np.array([[1,2],[3,4]])
b=np.array([[5,6],[7,8]])
np.matmul(a,b)

array([[19, 22],
       [43, 50]])

In [57]:
a*b

array([[ 5, 12],
       [21, 32]])

In [59]:
#Another method to perfrom matrix product
a.dot(b)

array([[19, 22],
       [43, 50]])

#### Indexing and slicing

In [60]:
a=np.array([6,7,8])
a[0:2]

array([6, 7])

In [61]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [62]:
a[-1,2] #[row,column]

9

In [66]:
a[:,1:]

array([[2, 3],
       [5, 6],
       [8, 9]])

In [67]:
a[:,1:2:2]

array([[2],
       [5],
       [8]])

#### applying for loop

In [68]:
for row in a:
    print(row)

[1 2 3]
[4 5 6]
[7 8 9]


In [78]:
for row in a:
    print(row[1])

2
5
8


In [75]:
a.ndim

2

In [76]:
a[1,2]

6

In [79]:
for cell in a.flat:
    print(cell)


1
2
3
4
5
6
7
8
9


#### Stacking of arrays

In [84]:
a=np.arange(6).reshape(3,2)
b=np.arange(6,12).reshape(3,2)
np.vstack([a,b])

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [85]:
np.hstack([a,b])

array([[ 0,  1,  6,  7],
       [ 2,  3,  8,  9],
       [ 4,  5, 10, 11]])

splitting arrays

In [86]:
a=np.arange(30).reshape(2,15)
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [89]:
result=np.hsplit(a,3)
result

[array([[ 0,  1,  2,  3,  4],
        [15, 16, 17, 18, 19]]), array([[ 5,  6,  7,  8,  9],
        [20, 21, 22, 23, 24]]), array([[10, 11, 12, 13, 14],
        [25, 26, 27, 28, 29]])]

In [90]:
result[0]

array([[ 0,  1,  2,  3,  4],
       [15, 16, 17, 18, 19]])

In [91]:
result[1]

array([[ 5,  6,  7,  8,  9],
       [20, 21, 22, 23, 24]])

In [93]:
result=np.vsplit(a,2)
result

[array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14]]),
 array([[15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])]

#### Indexing with boolean arrays

In [94]:
a=np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [95]:
b=a>4
b

array([[False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True]])

In [96]:
a[b]

array([ 5,  6,  7,  8,  9, 10, 11])