In [2]:
a= [1,3,5]
b= [2,4,6]
a+b

[1, 3, 5, 2, 4, 6]

##### If try to multiply two list then it will show error

In [13]:
a= [1,3,5]
b= [2,4,6]
a*b

TypeError: can't multiply sequence by non-int of type 'list'

In [9]:
import numpy as np
a=np.array([1,3,5])
b=np.array([2,4,6])
a*b

array([ 2, 12, 30])

In [11]:
a=np.array((1,3,5))
b=np.array((2,4,6))
type(a*b)

numpy.ndarray

In [12]:
a=np.array([1,3,5])
b=np.array([2,4,6])
type(a*b)

numpy.ndarray

In [ ]:
import numpy as np

In [14]:
a=np.array([1,2,3])
a

array([1, 2, 3])

In [15]:
a=np.array([1,2,3])
print(a)

[1 2 3]


In [17]:
b=np.array([[1,2,3],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


##### get dimesnion

In [19]:
a.ndim

1

In [20]:
b.ndim

2

##### get shape

In [21]:
a.shape

(3,)

In [22]:
b.shape

(2, 3)

numpy always takes by default 4 bytes(32 bits) for each item in array

##### get datatype

In [23]:
a.dtype

dtype('int32')

In [25]:
b.dtype

dtype('int32')

##### We can adjust its size manually by our choice

In [27]:
a=np.array([1,2,3],dtype='int16')

In [28]:
a.dtype

dtype('int16')

##### get size

In [29]:
a.itemsize

2

In [30]:
b.itemsize

4

In [32]:
a=np.array([1,2,3],dtype='int32')
a.itemsize

4

##### Total size of an element

In [33]:
a.size

3

##### get totalsize

In [35]:
a.size*a.itemsize

12

In [36]:
a.nbytes

12

##### get size in flot type

In [39]:
c=np.array([[7.0,8.0,9.0],[4.0,5.0,6.0]])
c.itemsize


8

In [40]:
c.size

6

Accessing/changing specific elements,rows,column,etc

In [41]:
a= np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
a.shape

(2, 7)

In [44]:
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


#### get specific element [r,c]

In [42]:
a[1,5]

13

In [43]:
a[1,-2]

13

get specific row

In [45]:
a[1,:]

array([ 8,  9, 10, 11, 12, 13, 14])

In [46]:
a[0,:]

array([1, 2, 3, 4, 5, 6, 7])

In [47]:
a[:,:]

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14]])

get specific column

In [48]:
a[:,2]

array([ 3, 10])

##### getting a little bit more fancy[startingindex:endindex:stepsize]

In [52]:
a[0,1:6:2]

array([2, 4, 6])

In [53]:
a[1,1:6:2]

array([ 9, 11, 13])

In [55]:
a[0,1:-2:2] # for 0th row and start from 2nd element(1 as per list nomenclature) and end up to -2(-2 excluded)and step size of 2

array([2, 4])

In [56]:
a[1,5]=20
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]


In [57]:
a[:,2]=5
print(a)

array([[ 1,  2,  5,  4,  5,  6,  7],
       [ 8,  9,  5, 11, 12, 20, 14]])

##### 3dimensional example

In [60]:
b=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


##### get specific element. (work outside in)

In [62]:
b[0,0,0]

1

In [63]:
b[0,0,1]

2

In [64]:
b.shape

(2, 2, 2)

In [65]:
b[:,1,:]

array([[3, 4],
       [7, 8]])

In [66]:
b[:,1,0]

array([3, 7])

In [67]:
b[0,1,:]

array([3, 4])

##### replace

In [68]:
b[:,1,:]=[[8,8],[20,20]]

In [69]:
b

array([[[ 1,  2],
        [ 8,  8]],

       [[ 5,  6],
        [20, 20]]])

if we will try to replace with out of scope array it will throw error

In [70]:
b[:,1,:]=[[8,8,8],[20,20]]

ValueError: setting an array element with a sequence.

#### Initializing different type of array

##### all 0's matrix

In [72]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [73]:
np.zeros((5,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [75]:
np.zeros((5,2,2,3)) #4d array

array([[[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]]])

#### all 1's matrix

In [76]:
np.ones((2,2,2))

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

#Any other Number apart from 0's and 1's matrix

In [77]:
np.full((2,2),99)

array([[99, 99],
       [99, 99]])

In [79]:
np.full((2,2),(98,99))

array([[98, 99],
       [98, 99]])

In [80]:
np.full((2,2),(98,99),dtype='float32')

array([[98., 99.],
       [98., 99.]], dtype=float32)

#any other Number(full_like)

In [81]:
a

array([[ 1,  2,  5,  4,  5,  6,  7],
       [ 8,  9,  5, 11, 12, 20, 14]])

In [83]:
np.full(a.shape,4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [84]:
np.full_like(a,4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

##### Raise a matrix of random number of decimal values

In [86]:
np.random.rand(4,2)

array([[0.01386376, 0.42718571],
       [0.35482121, 0.44292111],
       [0.7503203 , 0.23959337],
       [0.28860817, 0.5563727 ]])

In [87]:
np.random.random_sample(a.shape)

array([[0.97757757, 0.2923022 , 0.0888334 , 0.68616361, 0.1521379 ,
        0.33951473, 0.89277962],
       [0.67884366, 0.77493148, 0.61328324, 0.19406463, 0.21353354,
        0.01482798, 0.14075874]])

##### for random integer values

In [89]:
np.random.randint(7,size=(3,3))

array([[3, 3, 2],
       [6, 3, 4],
       [2, 1, 1]])

In [90]:
np.random.randint(4,7,size=(3,3))

array([[5, 4, 5],
       [6, 6, 4],
       [6, 6, 6]])

In [91]:
np.random.randint(-2,7,size=(3,3))

array([[-1,  6,  1],
       [ 5,  0,  3],
       [ 4,  6, -2]])

#### Identitiy matrix

In [93]:
np.identity(2)

array([[1., 0.],
       [0., 1.]])

In [94]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [96]:
arr=np.array([1,2,3])
r1=np.repeat(arr,3)
print(r1)

[1 1 1 2 2 2 3 3 3]


In [97]:
arr=np.array([1,2,3])
r1=np.repeat(arr,3,axis=0)
print(r1)

[1 1 1 2 2 2 3 3 3]


In [99]:
arr=np.array([[1,2,3]])
r1=np.repeat(arr,3,axis=1)
print(r1)

[[1 1 1 2 2 2 3 3 3]]


In [100]:
arr=np.array([[1,2,3]])
r1=np.repeat(arr,3,axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [101]:
output=np.ones((5,5))
output

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [103]:
z=np.zeros((3,3))
z[1,1]=9
z

array([[0., 0., 0.],
       [0., 9., 0.],
       [0., 0., 0.]])

In [104]:
output[1:4,1:4]=z
output

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 9., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

In [105]:
a=np.array([1,2,3])
b=a
b[0]=100
print(b)

[100   2   3]


In [106]:
print(a)

[100   2   3]


In [107]:
a=[1,2,3]
b=a
b[0]=100
print(a)

[100, 2, 3]


In [108]:
a=np.array([1,2,3])
b=a.copy()
b[0]=100
print(a)

[1 2 3]


#### Mathematics

In [121]:
a=np.array([1,2,3,4])


In [114]:
a+=2
a

array([3, 4, 5, 6])

In [116]:
a

array([1, 2, 3, 4])

In [117]:
a+2

array([3, 4, 5, 6])

In [122]:
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [123]:
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

#### Linear Algebra

In [125]:
a=np.ones((2,3))
a

array([[1., 1., 1.],
       [1., 1., 1.]])

In [126]:
b=np.full((3,2),(2,4))
b

array([[2, 4],
       [2, 4],
       [2, 4]])

#### Matrix Multiply

In [127]:
np.matmul(a,b)

array([[ 6., 12.],
       [ 6., 12.]])

In [128]:
c=np.identity(3)
c

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### Find determinant of matrix

In [129]:
np.linalg.det(c)

1.0

### Statistics

In [130]:
stats=np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [131]:
np.min(stats)

1

In [132]:
np.min(stats,axis=1)

array([1, 4])

In [133]:
np.max(stats)

6

In [134]:
np.min(stats,axis=0)

array([1, 2, 3])

In [135]:
np.sum(stats)

21

In [136]:
np.sum(stats,axis=1)

array([ 6, 15])

In [137]:
np.sum(stats,axis=0)

array([5, 7, 9])

#### Reorganizing Arrays

In [141]:
before=np.array([[1,2,3,4],[5,6,7,8]])
print(before)

[[1 2 3 4]
 [5 6 7 8]]


In [142]:
before.shape

(2, 4)

In [143]:
after =before.reshape((8,1))
print(after)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]


##### Vertically stacking vectors

In [144]:
v1=np.array([1,2,3,4])
v2=np.array([5,6,7,8])
np.vstack([v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [145]:
np.vstack([v1,v2,v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [146]:
np.hstack([v1,v2])

array([1, 2, 3, 4, 5, 6, 7, 8])

#### Miscellaneous

##### Load data From file

In [148]:
np.genfromtxt('data.txt',delimiter=',')

array([[  1.,  13.,  21.,  11., 196.,  75.,   4.,   3.,  34.,   6.,   7.,
          8.,   0.,   1.,   2.,   3.,   4.,   5.],
       [  3.,  42.,  12.,  33., 766.,  75.,   4.,  55.,   6.,   4.,   3.,
          4.,   5.,   6.,   7.,   0.,  11.,  12.],
       [  1.,  22.,  33.,  11., 999.,  11.,   2.,   1.,  78.,   0.,   1.,
          2.,   9.,   8.,   7.,   1.,  76.,  88.]])

In [149]:
datafile=np.genfromtxt('data.txt',delimiter=',')
datafile

array([[  1.,  13.,  21.,  11., 196.,  75.,   4.,   3.,  34.,   6.,   7.,
          8.,   0.,   1.,   2.,   3.,   4.,   5.],
       [  3.,  42.,  12.,  33., 766.,  75.,   4.,  55.,   6.,   4.,   3.,
          4.,   5.,   6.,   7.,   0.,  11.,  12.],
       [  1.,  22.,  33.,  11., 999.,  11.,   2.,   1.,  78.,   0.,   1.,
          2.,   9.,   8.,   7.,   1.,  76.,  88.]])

In [150]:
datafile.astype('int32')

array([[  1,  13,  21,  11, 196,  75,   4,   3,  34,   6,   7,   8,   0,
          1,   2,   3,   4,   5],
       [  3,  42,  12,  33, 766,  75,   4,  55,   6,   4,   3,   4,   5,
          6,   7,   0,  11,  12],
       [  1,  22,  33,  11, 999,  11,   2,   1,  78,   0,   1,   2,   9,
          8,   7,   1,  76,  88]])

In [151]:
datafile

array([[  1.,  13.,  21.,  11., 196.,  75.,   4.,   3.,  34.,   6.,   7.,
          8.,   0.,   1.,   2.,   3.,   4.,   5.],
       [  3.,  42.,  12.,  33., 766.,  75.,   4.,  55.,   6.,   4.,   3.,
          4.,   5.,   6.,   7.,   0.,  11.,  12.],
       [  1.,  22.,  33.,  11., 999.,  11.,   2.,   1.,  78.,   0.,   1.,
          2.,   9.,   8.,   7.,   1.,  76.,  88.]])

In [152]:
filedata=datafile.astype('int32')
filedata

array([[  1,  13,  21,  11, 196,  75,   4,   3,  34,   6,   7,   8,   0,
          1,   2,   3,   4,   5],
       [  3,  42,  12,  33, 766,  75,   4,  55,   6,   4,   3,   4,   5,
          6,   7,   0,  11,  12],
       [  1,  22,  33,  11, 999,  11,   2,   1,  78,   0,   1,   2,   9,
          8,   7,   1,  76,  88]])

#### Boolean masking and Advanced indexing

In [153]:
filedata>50

array([[False, False, False, False,  True,  True, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True,  True, False,  True, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True, False, False, False,  True,
        False, False, False, False, False, False, False,  True,  True]])

In [154]:
filedata[filedata>50]

array([196,  75, 766,  75,  55, 999,  78,  76,  88])

In [158]:
#You can index with a list in numpy
a=np.array([1,2,3,4,5,6,7,8])
a[[1,2,7]]

array([2, 3, 8])

In [159]:
np.any(filedata>50,axis=0)# axis=0 for column wise and 1 for row wise

array([False, False, False, False,  True,  True, False,  True,  True,
       False, False, False, False, False, False, False,  True,  True])

In [160]:
np.all(filedata>50,axis=0)

array([False, False, False, False,  True, False, False, False, False,
       False, False, False, False, False, False, False, False, False])

In [161]:
(filedata>50)& (filedata<100)

array([[False, False, False, False, False,  True, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False,  True, False,  True, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False,  True,
        False, False, False, False, False, False, False,  True,  True]])

In [162]:
(~((filedata>50)& (filedata<100)))

array([[ True,  True,  True,  True,  True, False,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True, False,  True, False,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True, False,
         True,  True,  True,  True,  True,  True,  True, False, False]])